- name: Install repo yum
  template:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/anydesk.repo
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.repo"
    - "{{ ansible_distribution | lower }}.repo"
    - "repo.j2"

- name: Install AndyDesk
  yum:
    name: anydesk
    state: present
  ignore_errors: "{{ ansible_check_mode }}"


