- name: Install repo dnf
  template:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/anydesk.repo
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.repo"
    - "{{ ansible_distribution | lower }}.repo"
    - "repo.j2"
  become: true

- name: Install AndyDesk
  become: true
  dnf:
    name: anydesk
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  #when: "{{ ansible_check_mode | bool }} == 'false'"

